name: FastAPI CI/CD

on:
  push:
    branches: main

jobs:
  build:
    name: Build FastAPI
    runs-on: ubuntu-latest
       
    steps:
    
    - name: Copia os arquivos do repositório
      uses: actions/checkout@v4

    - name: Informa versão python - 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'    
  
    - name: Instalar Depedencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests    
      env:
        PYTHONPATH: ${{ github.workspace }}  # Adiciona o diretório do projeto ao PYTHONPATH
      run: |
        pytest tests/

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   

    - name: Build e enviar para Docker image     
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fernandos/app-fastapi-demo:latest, fernandos/app-fastapi-demo:${{ github.run_number }}